[package]
name = "build_metadata"
version = "0.1.0"
authors = ["Geoffroy Couprie <geo.couprie@gmail.com>"]

[lib]
name = "build_metadata"
plugin = true

[dependencies]
git2 = { version = "0.4", default-features = false, features = [] }
